### PR TITLE
Replace the phrase "feature set" with dialect

### PR DESCRIPTION
**Pull request by Relequestual**
Made it clearer that the value of $schema is a dialect identifier,

### CODE REVIEW

**Comment by ssilverman** [comment]
I don't love the word "dialect" because it, to me, implies a whole new interpretation of JSON schema. I much prefer "feature set". This is just my opinion and I'm not proposing you change it back if "dialect" is the final choice.

**Comment by Relequestual** [comment]
It's analogous to SQL which has different dialects.

**Comment by handrews** [comment]
"dialect" came from me explaining this stuff to various people, including on consulting contracts.  It was effective and seemed easily understood.  My sample size is not huge, but there was certainly zero resistance to it.  Folks noted that it fits well with "vocabulary."  And @Relequestual , SQL dialects are a good analogue for explaining this, and a well-established precedent.

**Comment by ssilverman** [comment]
If it works, it works.

**Review by ssilverman — APPROVED** [review]
👍

**Review by handrews — APPROVED** [review]

**Pull request merged**
