### PR TITLE
remove 'mathematical integers' section

### LINKED ISSUE #898: Integers need further clarification
There's still an ambiguity when defining an integer. (Note: This issue isn't here to debate how one defines an "integer" for JSON schemas.)

It says in [core/section 6.3](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.6.3):
> "For consistency, integer JSON numbers SHOULD NOT be encoded with a fractional part."

TLDR: Does "encoded with a fractional part" mean "encoded internally after processing the JSON" or "a floating point number having a zero fractional part encoded as the JSON `1.0`"? Another way of putting it: "Is the written JSON number `1.0` considered to be encoded with a fractional part since it has the `.0` there?"

There's an ambiguity with how this is phrased. Immediately above this sentence, it mentions that numbers may have "different internal representations." This implies "a number encoded to an internal representation." However, when we speak of JSON documents, we can think of a number "encoded into its JSON format."

For the first case, the `int` 1 is encoded internally as `1` and has no fractional part, and the `float` 1.0 is encoded internally as `1.0`, which has a fractional part of zero.

For the second case, depending on the parser, the "JSON-encoded" number could end up as either an "internally-encoded" float with a zero fractional part in the case of JavaScript, or as either an "internally-encoded" `int` or `float` or even "arbitrary-precision decimal or integer" in other languages, depending on the parser.

So my question is: What does it mean to "not be encoded with a fractional part"? Does this mean: "no empty fractional part _and_ no zero-valued fractional part", or does it just mean "no empty fractional part"? i.e. how does a "zero-valued fractional part" fit in here?

Also see: #79 and json-schema-org/JSON-Schema-Test-Suite#132

### PR DESCRIPTION
**Pull request by gregsdennis**
Resolves #898 

After wordsmithing something that sounded approximately right, I found [Instance Equality](https://json-schema.org/draft/2020-12/json-schema-core.html#name-instance-equality), which pretty much clears up any debate in my mind.

### CODE REVIEW

**Review by Relequestual — APPROVED** [review]
As per https://github.com/json-schema-org/json-schema-spec/issues/898#issuecomment-619477774
I agree, I don't think JSON encoding is within scope of the JSON Schema spec.

**Review by Julian — APPROVED** [review]

**Review by jdesrosiers — APPROVED** [review]

**Comment by TomWright** [comment]
> PR can be merged after Fri Sep 22 2023 05:45:26 GMT+0000 (Coordinated Universal Time)

It has now passed this date - any chance we can get this merged? It's causing me some problems.

**Comment by gregsdennis** [comment]
Merging the PR isn't going to help in the near term any. This is merging into an unpublished document.

If you like, come join us in slack or start a discussion in the community repo and we can help you with out your problem.

**Comment by jdesrosiers** [comment]
I just noticed when building the spec to review another change that removing this section caused a couple broken links.

```
> @json-schema-org/json-schema-spec@1.0.0 build-core
> node build/build.js < jsonschema-core.md > jsonschema-core.html

2757:1-2757:17 warning Link to unknown heading: `integers` missing-heading remark-validate-links
2778:1-2778:17 warning Link to unknown heading: `integers` missing-heading remark-validate-links
```

**Pull request merged**
