### PR TITLE
Update jsonschema-validation.md - fix Typo

### PR DESCRIPTION
**Pull request by LasneF**
fixing https://github.com/json-schema-org/json-schema-spec/issues/1356

### CODE REVIEW

**Review by benjagm — APPROVED** [review]
Thanks for fixing this @LasneF !

**Comment by LasneF** [comment]
@benjagm what about merging ?
#Less PR , less Conflict :)

**Comment by benjagm** [comment]
> @benjagm what about merging ? #Less PR , less Conflict :)

I was waiting for any of the spec authors to review it as! Let me see if someone can review it! Thanks for your patience!

**Review by Relequestual — APPROVED** [review]
My first PR was to fix a typo! Always welcome!

**Review by gregsdennis — APPROVED** [review]

**Pull request merged**
