### PR TITLE
Boolean operators are boolean operators

### LINKED ISSUE #910: Section 9.2.1 (*Of keywords) is non-specific about sequencing
This may be irrelevant to the [test case](https://github.com/json-schema-org/JSON-Schema-Test-Suite/issues/359) that highlighted the issue to me, but it seems that the spec should say whether sequence of evaluation is important.

### PR DESCRIPTION
**Pull request by handrews**
This has been reported as a point of confusion.

Fixes #910

### CODE REVIEW

**Comment by Relequestual** [comment]
I don't have any problems with the PR, although I'm not familiar with those terms.
I wasn't convinced the associated issue actually required any changes.
I still feel like the words we have were enough to convey the requirements, but we didn't get a subsequent response from @gregsdennis on the issue.

**Comment by handrews** [comment]
@Relequestual which terms- commutativity and associativity?

https://en.wikipedia.org/wiki/Commutative_property
https://en.wikipedia.org/wiki/Associative_property

**Comment by Relequestual** [comment]
Yeah. I mean I used google and they made sense. I obviously didn't study that aspect of maths I guess.

**Comment by handrews** [comment]
@Relequestual to be fair, the grammatical forms `commutativity` and `associativity` are probably not the most recognizable forms.  But they do come up easily in a google search and I like that they are precisely defined.

**Comment by gregsdennis** [comment]
I don't think associativity is needed.  It describes how terms are grouped, but subschemas aren't grouped at all within a `*Of`, they're just listed.

Commutativity (ordering of terms) should be sufficient.

**Comment by handrews** [comment]
I still don't even understand why I have to explain commutativity so I'd rather just cover all the bases I guess.

**Comment by gregsdennis** [comment]
For reference:

Associativity:

```
(a + b) + c = a + (b + c)
```

Commutativity:

```
a + b = b + a
```

**Comment by Relequestual** [comment]
@gregsdennis FYI still waiting to hear re: https://github.com/json-schema-org/json-schema-spec/issues/910#issuecomment-660594604

**Comment by handrews** [comment]
> @gregsdennis FYI still waiting to hear re: #910 (comment)

Yeah I'm also happy to just drop this PR.

What I don't want to do is write something that facilitates the expectation that things are ordered unless explicitly stated otherwise.  These are boolean operators.  They act like boolean operators and that's more important than JSON syntax.

**Comment by gregsdennis** [comment]
Happy to drop

**Comment by handrews** [comment]
@gregsdennis cool, thanks!

**Pull request closed without merging**
