### PR TITLE
Add namedExamples

### PR DESCRIPTION
**Pull request by K-Adam**
#1074

### CODE REVIEW

**Review by gregsdennis — COMMENTED** [review]
Thanks for preempting this change. I think that it needs a bit more discussion, though. We don't typically add keywords to the base schema lightly.

I'll leave further comments in the issue.

**Comment by handrews** [comment]
Even if accepted, this also needs to be changed to target the `draft-next` branch rather than `master`.

**Comment by K-Adam** [comment]
@handrews The [Guidelines for contributing](https://github.com/json-schema-org/json-schema-spec/blob/draft-next/CONTRIBUTING.md) mentioned, that "Pull requests should be made to master"

**Comment by handrews** [comment]
@K-Adam oops, thanks, it's a recent change, forgot to update the file.

**Pull request closed without merging**
