### PR TITLE
Add Henry Andrews, author

### PR DESCRIPTION
**Pull request by awwright**
@handrews Can I get your sign-off on this PR's accuracy?

### CODE REVIEW

**Comment by handrews** [comment]
Should be "Cloudflare, Inc." (see https://tools.ietf.org/html/draft-ietf-regext-dnsoperator-to-rrr-protocol-01 for an example)

but otherwise looks great, thanks!

**Comment by awwright** [comment]
@handrews Updated

Most documents seem to prefer the trade name over the legal name, but it doesn't seem to matter either way

**Comment by handrews** [comment]
@awwright looking through the results at
https://www.google.com/#q=site:tools.ietf.org+cloudflare

all but one have the "Inc."  So it could go either way, I was just going with the obvious majority.  Although https://tools.ietf.org/html/rfc7710 does not have the "Inc."  So do whichever, I doubt our legal department is going to chase after me either way.

**NOTE**:  "Cloudflare" is correct, ignore the older ones with "CloudFlare".  We thankfully got rid of the capital F recently.

**Comment by awwright** [comment]
Welcome aboard 🚢

**Pull request merged**
