### PR TITLE
Add minContains and maxContains

### PR DESCRIPTION
**Pull request by handrews**
Addresses #441

### CODE REVIEW

**Comment by handrews** [comment]
Two-day warning!  If anyone else wants to comment on this you have two days before we hit the two week threshold, at which point I will merge it (since there is one approval already.)

**Comment by epoberezkin** [comment]
@handrews do you think it is worth adding the note about `minContains: 0` that it essentially makes contains doing nothing unless maxContains is present?

**Comment by handrews** [comment]
@epoberezkin thanks, updated.

**Comment by handrews** [comment]
Note that this is temporarily on hold pending decisions on whether to do an interim bugfix release.  It is not abandoned!

**Pull request merged**
