### PR TITLE
Move up the JSON Hyper Schema in "mailto:" example

### PR DESCRIPTION
**Pull request by dlax**
While reading this section, I felt that the example came too late after
a lot of explanation on it. So moving it up just after its introduction
paragraph.

### CODE REVIEW

**Comment by handrews** [comment]
I generally like this, although I think some aspect of explaining why/how `multipart/form-data` is modeled in JSON Hyper-Schema needs to be explained before the example.  It's just to weird to make sense of without a bit of lead-in.

**Comment by dlax** [comment]
> I think some aspect of explaining why/how multipart/form-data is modeled in JSON Hyper-Schema needs to be explained before the example.

Makes sense. As we cannot put all explanations before, we cannot either put them all after I guess.
I can move back the first (and maybe second) paragraph before, what do you think?

**Comment by handrews** [comment]
Yes, I think moving the first two paragraphs back would work nicely.

**Comment by dlax** [comment]
> Yes, I think moving the first two paragraphs back would work nicely.

Ok :)

I amended the commit and just force-pushed.

**Pull request merged**
